Repository ynput/ayon-ftrack, pull requests merged in 2024-10, with the labels that each got.

#138 Chore: Follow ftrack brand guidelines
  README.md
  client/ayon_ftrack/common/__init__.py
  client/ayon_ftrack/common/custom_attributes.py
  client/ayon_ftrack/common/event_handlers/ftrack_action_handler.py
  client/ayon_ftrack/common/event_handlers/ftrack_base_handler.py
  client/ayon_ftrack/common/event_handlers/ftrack_event_handler.py
  client/ayon_ftrack/common/ftrack_server.py
  client/ayon_ftrack/common/lib.py
  client/ayon_ftrack/event_handlers_to_convert/action_delete_old_versions.py
  client/ayon_ftrack/event_handlers_user/action_applications.py
  client/ayon_ftrack/event_handlers_user/action_client_review_sort.py
  client/ayon_ftrack/event_handlers_user/action_create_cust_attrs.py
  client/ayon_ftrack/event_handlers_user/action_create_folders.py
  client/ayon_ftrack/event_handlers_user/action_create_project_structure.py
  client/ayon_ftrack/event_handlers_user/action_delivery.py
  client/ayon_ftrack/ftrack_addon.py
  client/ayon_ftrack/launch_hooks/post_ftrack_changes.py
  client/ayon_ftrack/plugins/_unused_publish/integrate_ftrack_comments.py
  client/ayon_ftrack/plugins/launcher_actions/show_in_ftrack.py
  client/ayon_ftrack/plugins/publish/collect_custom_attributes_data.py
  client/ayon_ftrack/plugins/publish/collect_ftrack_api.py
  client/ayon_ftrack/plugins/publish/collect_ftrack_family.py
  client/ayon_ftrack/plugins/publish/collect_webpublisher_credentials.py
  client/ayon_ftrack/plugins/publish/integrate_ftrack_api.py
  client/ayon_ftrack/plugins/publish/integrate_ftrack_description.py
  client/ayon_ftrack/plugins/publish/integrate_ftrack_farm_status.py
  client/ayon_ftrack/plugins/publish/integrate_ftrack_instances.py
  client/ayon_ftrack/plugins/publish/integrate_ftrack_note.py
  client/ayon_ftrack/plugins/publish/integrate_ftrack_status.py
  client/ayon_ftrack/plugins/publish/integrate_hierarchy_ftrack.py
  client/ayon_ftrack/plugins/publish/validate_custom_ftrack_attributes.py
  client/ayon_ftrack/resources/sign_in_message.html
  client/ayon_ftrack/scripts/sub_user_server.py
  client/ayon_ftrack/tray/ftrack_tray.py
  client/ayon_ftrack/tray/login_dialog.py
  package.py
  server/__init__.py
  server/settings/main.py
  server/settings/publish_plugins.py
  service_tools/README.md
  services/leecher/leecher/listener.py
  services/processor/processor/default_handlers/action_delete_entities.py
  services/processor/processor/default_handlers/action_prepare_project.py
  services/processor/processor/default_handlers/action_private_project_detection.py
  services/processor/processor/default_handlers/event_push_frame_values_to_task.py
  services/processor/processor/default_handlers/event_sync_from_ftrack.py
  services/processor/processor/default_handlers/event_task_to_version_status.py
  services/processor/processor/handlers_to_convert/event_sync_to_avalon.py
  services/processor/processor/lib/sync_from_ftrack.py
  services/processor/processor/server.py
Labels: type: enhancement

#144 Sync: Sync start/end date and description
  services/processor/processor/default_handlers/event_sync_from_ftrack.py
  services/processor/processor/lib/sync_from_ftrack.py
Labels: type: enhancement

#147 Sync: Folder and Task statuses
  service_tools/requirements.txt
  services/leecher/pyproject.toml
  services/processor/processor/default_handlers/event_sync_from_ftrack.py
  services/processor/processor/lib/sync_from_ftrack.py
  services/processor/pyproject.toml
Labels: type: enhancement

#150 Remove Standalone publisher settings
  server/settings/publish_plugins.py
Labels: type: enhancement

#152 Sync: Prepare for ayon api change
  services/processor/processor/lib/sync_from_ftrack.py
Labels: type: enhancement

#151 Users: Sync users
  server/settings/service_handlers.py
  services/processor/processor/default_handlers/action_prepare_project.py
  services/processor/processor/default_handlers/action_sync_users.py
  services/processor/processor/default_handlers/event_users_sync_from_ftrack.py
  services/processor/processor/lib/__init__.py
  services/processor/processor/lib/users.py
Labels: type: feature

#153 Event handlers: Add cleanup method
  client/ayon_ftrack/common/event_handlers/ftrack_base_handler.py
  client/ayon_ftrack/common/ftrack_server.py
  services/processor/processor/default_handlers/action_create_lists.py
  services/processor/processor/handlers_to_convert/action_create_review_session.py
  services/processor/processor/server.py
Labels: type: enhancement

#154 Service tools: Fake 'ftrack_common.event_handlers'
  service_tools/main.py
Labels: type: maintenance
