Repository ynput/ayon-ftrack, pull requests merged in 2024-09, with the labels that each got.

#120 Event handlers: Status task to version settings
  server/settings/service_handlers.py
Labels: type: bug, type: enhancement

#135 Add show in ftrack launcher action
  client/ayon_ftrack/ftrack_addon.py
  client/ayon_ftrack/plugins/launcher_actions/show_in_ftrack.py
  client/ayon_ftrack/resources/ftrack_icon.png
Labels: type: enhancement, sponsored

#139 Chore: Stricter ruff
  client/ayon_ftrack/common/event_handlers/__init__.py
  client/ayon_ftrack/event_handlers_user/action_delivery.py
  client/ayon_ftrack/plugins/publish/integrate_ftrack_api.py
  ruff.toml
  server/settings/service_handlers.py
  services/leecher/leecher/__init__.py
  services/processor/processor/__init__.py
  services/processor/processor/default_handlers/event_sync_from_ftrack.py
Labels: type: maintenance
