Repository ynput/ayon-ftrack, pull requests merged in 2024-12, with the labels that each got.

#175 Processor: Fail stuck process events
  services/processor/processor/ftrack_session.py
Labels: type: enhancement

#176 Download review media action
  client/ayon_ftrack/event_handlers_user/action_download_reviews.py
Labels: sponsored, type: feature

#173 AYON to ftrack sync: Sync comments
  client/ayon_ftrack/plugins/publish/integrate_ftrack_note.py
  server/settings/publish_plugins.py
  services/processor/processor/default_handlers/event_sync_comments.py
  services/transmitter/transmitter/logic.py
  services/transmitter/transmitter/service.py
Labels: type: enhancement

#180 Fill environment variables for farm jobs
  client/ayon_ftrack/plugins/publish/collect_farm_env_variables.py
Labels: type: enhancement

#181 Chore: Fix transmitter service manage script
  services/transmitter/Dockerfile
  services/transmitter/manage.ps1
Labels: type: bug

#182 Services: Fix event summary
  services/leecher/leecher/listener.py
  services/processor/processor/server.py
  services/transmitter/transmitter/service.py
Labels: type: bug

#183 Transmitter: Fix statuses fetching from ftrack
  services/processor/processor/lib/sync_from_ftrack.py
  services/transmitter/transmitter/logic.py
Labels: type: bug

#186 Wepublisher: use service account to query secrets
  client/ayon_ftrack/plugins/publish/collect_webpublisher_credentials.py
Labels: type: bug, sponsored

#187 Sync folder/task types and statuses on project sync
  services/processor/processor/default_handlers/event_sync_from_ftrack.py
  services/processor/processor/lib/sync_from_ftrack.py
Labels: type: enhancement

#194 Collect ftrack family defaults
  server/settings/publish_plugins.py
Labels: type: enhancement
