Repository ynput/ayon-ftrack, pull requests merged in 2025-03, with the labels that each got.

#207 Integrate hierarchy: Add missing argument
  client/ayon_ftrack/plugins/publish/integrate_hierarchy_ftrack.py
Labels: type: bug

#210 Chore: Make settings model classes unique
  server/settings/desktopapp_handlers.py
  server/settings/service_handlers.py
Labels: type: enhancement

#211 To AYON sync: Reverse order of project statuses on sync
  services/processor/processor/lib/sync_from_ftrack.py
Labels: type: bug, sponsored

#215 Automated mkdocs setup
  .gitignore
  docs/css/custom.css
  docs/img/ay-symbol-blackw-full.png
  docs/img/favicon.ico
  docs/index.md
  docs/license.md
  mkdocs.yml
  mkdocs_hooks.py
  pyproject.toml
  uv.lock
Labels: type: feature

#216 Chore: Prepare project does set auto sync based on selected value
  services/processor/processor/default_handlers/action_prepare_project.py
Labels: type: bug, sponsored

#214 Integrate Hierarchy: Fix attribute configurations existence check
  client/ayon_ftrack/plugins/publish/integrate_hierarchy_ftrack.py
Labels: type: bug, sponsored
